---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${SERVICE_NAME}
  name: ${SERVICE_NAME}
spec:
  # replicas: ${REPLICAS}
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
      - image: ${CONTAINER_IMAGE}
        imagePullPolicy: Always
        name: ${SERVICE_NAME}
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: warehouse-kafka-kafka-bootstrap:9092
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: STOCKS_SVC
            value: stocks-service
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8082
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 7
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8082
          initialDelaySeconds: 1
          periodSeconds: 15
          timeoutSeconds: 7
        terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${SERVICE_NAME}
  name: ${SERVICE_NAME}
spec:
  ports:    
  - port: 8082
    protocol: TCP
    targetPort: 8082
    name: http
  selector:
    app: ${SERVICE_NAME}
  type: LoadBalancer
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: ${SERVICE_NAME}
  name: ${SERVICE_NAME}
spec:
  to:
    kind: Service
    name: ${SERVICE_NAME}
    weight: 100