---
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: warehouse-kafka
spec:
  kafka:
    version: 2.4.0
    replicas: 1
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.4"
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: orders-topic
  labels:
    strimzi.io/cluster: warehouse-kafka
spec:
  partitions: 1
  replicas: 1
  topicName: orders
  # config:
  #   retention.ms: 7200000
  #   segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: processed-orders-topic
  labels:
    strimzi.io/cluster: warehouse-kafka
spec:
  partitions: 1
  replicas: 1
  topicName: processed-orders
  # config:
  #   retention.ms: 7200000
  #   segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: events-topic
  labels:
    strimzi.io/cluster: warehouse-kafka
spec:
  partitions: 1
  replicas: 1
  topicName: events
  # config:
  #   retention.ms: 7200000
  #   segment.bytes: 1073741824