---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orders-service
  name: orders-service
  namespace: warehouse
spec:
  # replicas: ${REPLICAS}
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
      - image: quay.io/famargon/orders-service-kafka:latest
        imagePullPolicy: Always
        name: orders-service
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: warehouse-kafka-kafka-bootstrap:9092
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: STOCKS_SVC
            value: stocks-service
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8082
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 7
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8082
          initialDelaySeconds: 1
          periodSeconds: 15
          timeoutSeconds: 7
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orders-service
  name: orders-service
  namespace: warehouse
spec:
  ports:    
  - port: 8082
    protocol: TCP
    targetPort: 8082
    name: http
  selector:
    app: orders-service
  type: ClusterIP
