---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stocks-service
  name: stocks-service
  namespace: warehouse
spec:
  # replicas: ${REPLICAS}
  replicas: 1
  selector:
    matchLabels:
      app: stocks-service
  template:
    metadata:
      labels:
        app: stocks-service
    spec:
      containers:
      - image: quay.io/famargon/stocks-service-kafka:latest
        imagePullPolicy: Always
        name: stocks-service
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: warehouse-kafka-kafka-bootstrap:9092
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MONGO_USER
            value: admin
          - name: MONGO_PWD
            value: password
          - name: MONGO_HOSTS
            value: mongo-database:27017
          - name: MONGO_TLS
            value: false
          - name: MONGO_TLS_INSECURE
            value: false
          - name: MONGO_REPLICASET
            value: rs0
          - name: MONGO_AUTHSOURCE
            value: warehouse
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 7
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8081
          initialDelaySeconds: 1
          periodSeconds: 15
          timeoutSeconds: 7
        terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stocks-service
  name: stocks-service
  namespace: warehouse
spec:
  ports:    
  - port: 8081
    protocol: TCP
    targetPort: 8081
    name: http
  selector:
    app: stocks-service
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: stocks-service
  name: stocks-service
  namespace: warehouse
spec:
  to:
    kind: Service
    name: stocks-service
    weight: 100
