---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: warehouse-service
  name: warehouse-service
  namespace: warehouse
spec:
  # replicas: ${REPLICAS}
  replicas: 1
  selector:
    matchLabels:
      app: warehouse-service
  template:
    metadata:
      labels:
        app: warehouse-service
    spec:
      serviceAccount: warehouse
      containers:
      - image: quay.io/famargon/warehouse-service-kafka:latest
        imagePullPolicy: Always
        name: warehouse-service
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: warehouse-kafka-kafka-bootstrap:9092
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: STOCKS_SVC
            value: stocks-service
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 7
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 15
          timeoutSeconds: 7
        terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: warehouse-service
  name: warehouse-service
  namespace: warehouse
spec:
  ports:    
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: warehouse-service
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: warehouse-service
  name: warehouse-service
  namespace: warehouse
spec:
  to:
    kind: Service
    name: warehouse-service
    weight: 100
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: warehouse 
  namespace: warehouse
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: warehouse
rules:
- apiGroups: [""]
  resources: ["pods","nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: warehouse
  namespace: warehouse 
subjects:
- kind: ServiceAccount 
  name: warehouse
  namespace: warehouse 
roleRef:
  kind: ClusterRole
  name: warehouse 
  apiGroup: rbac.authorization.k8s.io
