name: Build and Publish container images
on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
    branches: [master]
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'Apicurio'
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64

      - name: Build all
        run: make build

      - name: Login to quay.io
        if: github.event_name == 'push'
        run: docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Build container images and push to quay
        if: github.event_name == 'push'
        run: make publish